### ISSUE TITLE
pfSense FauxAPI - integration or cooperation?

### ISSUE THREAD

**Issue by ndejong** [opoplawski/ansible-pfsense#12]
Hi - I'm the author of https://github.com/ndejong/pfsense_fauxapi and also an avid user of Ansible so I do like your approach.

I wonder if there is a way we could (or should) integrate or co-operate?  It might make sense for example for FauxAPI to make it easy for ansible-pfsense to call FauxAPI directly (eg named pipe over ssh) thereby opening up all the FauxAPI function calls to ansible-pfsense.

Feel free to get in contact.

**Comment by opoplawski** [comment]
I've poked around a FauxAPI, but to be honest I'm not entirely sure it makes sense to integrate.  Unfortunately what we really need is a proper API for pfSense.  But if you have any concrete suggestions I'll try to take a look.
