### ISSUE TITLE
Problem with using module: operation not permitted

### ISSUE THREAD

**Issue by denyka** [opoplawski/ansible-pfsense#14]
Hello, I have some problems with using this module in my environment. 
`failed: [] (item={u'address': u'172.16.10.145 172.16.10.111', u'type': u'host', u'name': u'adservers', u'descr': u'Active Directory Servers', u'detail': u'ad1||ad2'}) => {"changed": false, "item": {"address": "172.16.10.145 172.16.10.111", "descr": "Active Directory Servers", "detail": "ad1||ad2", "name": "adservers", "type": "host"}, "module_stderr": "Shared connection to   closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/dneichev/.ansible/tmp/ansible-tmp-1552989321.67-99305010884620/AnsiballZ_pfsense_alias.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/dneichev/.ansible/tmp/ansible-tmp-1552989321.67-99305010884620/AnsiballZ_pfsense_alias.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/dneichev/.ansible/tmp/ansible-tmp-1552989321.67-99305010884620/AnsiballZ_pfsense_alias.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_pfsense_alias_payload_P6d4X3/__main__.py\", line 93, in <module>\r\n  File \"/tmp/ansible_pfsense_alias_payload_P6d4X3/__main__.py\", line 89, in main\r\n  File \"/tmp/ansible_pfsense_alias_payload_P6d4X3/ansible_pfsense_alias_payload.zip/ansible/module_utils/networking/pfsense/pfsense_alias.py\", line 178, in commit_changes\r\n  File \"/tmp/ansible_pfsense_alias_payload_P6d4X3/ansible_pfsense_alias_payload.zip/ansible/module_utils/networking/pfsense/pfsense.py\", line 403, in write_config\r\n  File \"/usr/local/lib/python2.7/shutil.py\", line 316, in move\r\n    copy2(src, real_dst)\r\n  File \"/usr/local/lib/python2.7/shutil.py\", line 145, in copy2\r\n    copystat(src, dst)\r\n  File \"/usr/local/lib/python2.7/shutil.py\", line 112, in copystat\r\n    os.utime(dst, (st.st_atime, st.st_mtime))\r\nOSError: [Errno 1] Operation not permitted: '/cf/conf/config.xml'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`
Can you help me to solve this problem?
I don't modificate any of ansible files and try to check how this module works.

**Comment by f-bor** [comment]
Hi,

The user you are using does not seem to have rights on the pfsense configuration file. Can you retry to run your playbook using the default admin user ?

**Comment by denyka** [comment]
I done this with
`become                = true
become_user           = root`
but no effect

**Comment by f-bor** [comment]
can you post your playbook and the ansible configuration for the pfsense host ?

**Comment by denyka** [comment]
Ok, thank you, it works for me. We can close this issue
