### ISSUE TITLE
ansible shell would not run on pfsense

### ISSUE THREAD

**Issue by ssbarnea** [opoplawski/ansible-pfsense#2]
because pfsense does not have a python installed by default, even trying to run shell module would give a failure.

I think we need to find a way to deal with this issue in order to make it possible to use common ansible modules.

**Comment by opoplawski** [comment]
Really?  python was installed on all of our pfsense boxes, I'm pretty sure without us doing anything.  I do have to set:
```
ansible_python_interpreter: /usr/local/bin/python2.7
```
though.  I guess I should put that in the readme.

**Comment by ssbarnea** [comment]
I will do more testing but I can assure you that on a clean 2.4.4 pfsense box, python command is not in PATH and ansible fails.

Still, I was able to run command on it by disabling gather_facts and using raw command. 

I recently started to write a playbook for pfsense so I will be back with more info. CC me if you want to contribute module to ansibe core, I would be glad to help.

**Comment by ssbarnea** [comment]
btw, there is a wip ticket to deal with similar issue on systems that have only python3 command, which is about adding some heuristics. it woud worth covering pfsense too.

**Comment by opoplawski** [comment]
Documented at be00bf0c421f4acac147e234f7da73375bc8c94e

I don't there is anything else that can be done here.

**Comment by denyka** [comment]
Hello, I have problems with run playbook with this module
`FAILED! => {"msg": "Could not find imported module support code for pfsense_alias.  Looked for either PFSenseAliasModule.py or pfsense_alias.py"}`

**Comment by opoplawski** [comment]
@denyka Please do not post unrelated posts in old issues.  Make sure your module_utils path is correct the and the ansible-pfsense module_utils files are there.  But again, please do not follow up here.
