### ISSUE TITLE
pfsense_user: KeyError when no password is provided

### ISSUE THREAD

**Issue by sbraz** [opoplawski/ansible-pfsense#20]
Hi,
I tried to use the module to change user attributes and it did not work without a password specified. I think you need this:
```diff
diff --git a/library/pfsense_user.py b/library/pfsense_user.py
index 13e4292..b731ed0 100644
--- a/library/pfsense_user.py
+++ b/library/pfsense_user.py
@@ -147,11 +147,12 @@ class pfSenseUser(object):
         changed = False
         stdout = None
         stderr = None
-        if re.match(r'\$2b\$', user['password']):
-            user['bcrypt-hash'] = user['password']
-        else:
-            self.module.fail_json(msg='Password (%s) does not appear to be a bcrypt hash' % user['password'])
-        del user['password']
+        if 'password' in user:
+            if re.match(r'\$2b\$', user['password']):
+                user['bcrypt-hash'] = user['password']
+            else:
+                self.module.fail_json(msg='Password (%s) does not appear to be a bcrypt hash' % user['password'])
+            del user['password']
         # Allow authorizedkeys to be clear or base64 encoded
         if 'authorizedkeys' in user and 'ssh-' in user['authorizedkeys']:
             user['authorizedkeys'] = base64.b64encode(user['authorizedkeys'])
```

**Comment by opoplawski** [comment]
The UI does not allow you to add a user without a password, so I think the proper fix is to make password a required argument to pfsense_user when state=present.

**Comment by opoplawski** [comment]
Ah, I follow now....

**Comment by sbraz** [comment]
> The UI does not allow you to add a user without a password, so I think the proper fix is to make password a required argument to pfsense_user when state=present.

With the change you made, can I edit an existing user without specifying its password? I simply needed to change the user's SSH public key but without knowledge of its password.

**Comment by opoplawski** [comment]
Yes - that was the realization I made afterwards.  It will require a password to create a new user, but not when modifying an existing one.
