### ISSUE TITLE
i'm unsure how you install this

### ISSUE THREAD

**Issue by loztagain** [opoplawski/ansible-pfsense#24]
Hi, I'm a little unsure how to being using this module.  It is the first custom one I've tried, and googling what to do is escaping me.
Where do you actually place all the files that are downloaded?
Thanks for your time.
Regards

**Comment by f-bor** [comment]
Hi,
You let them in a directory, let's say ~/ansible-pfsense. You have to run from ansible directory:

> source ./hacking/env-setup

Then you can write and run your playbooks from inside ~/ansible-pfsense.

Let me know if it's ok for you.

**Comment by loztagain** [comment]
lol

Thanks for response

I tried initially running from directory. It would have helped if I'd
shared that.

I get this message those:

TASK [HTTP allow rule]
*****************************************************************************************
task path: /home/aadmin/test/allowHTTP.yml:6
fatal: [fw1]: FAILED! => {
    "msg": "Could not find imported module support code for ('network',
'pfsense', 'pfsense').  Looked for either ip_network.py or ipaddress.py"
}
        to retry, use: --limit @/home/aadmin/test/allowHTTP.retry

**Comment by f-bor** [comment]
it seems that something is broken with your ansible installation. I'm not sure I can help.

Which ansible version are you using ?

**Comment by opoplawski** [comment]
Closing.  Please re-open if you can provide more information.
