### ISSUE TITLE
rule_separator: AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by WintyBe** [opoplawski/ansible-pfsense#26]
Hi,

Whenever I try to use the pfsense_rule_separator I get a "AttributeError: 'NoneType' object has no attribute 'find'" error. Tested in various ways (with rules, specifying the position, etc ...) and it only seems to trigger when you don't have any separators yet; if there are present, it works fine.

Playbook:

>     - name: Add rule separator
>       pfsense_rule_separator:
>         name: Test
>         state: present
>         interface: wan
>         color: danger

Full error:

> TASK [Add rule separator] *******************************************************************************************************************************************************************************************************************
> fatal: [192.0.2.110]: FAILED! => changed=false
>   module_stderr: |-
>     Shared connection to 192.0.2.110 closed.
>   module_stdout: |-
>     Traceback (most recent call last):
>       File "/root/.ansible/tmp/ansible-tmp-1567431318.58-16278943694065/AnsiballZ_pfsense_rule_separator.py", line 114, in <module>
>         _ansiballz_main()
>       File "/root/.ansible/tmp/ansible-tmp-1567431318.58-16278943694065/AnsiballZ_pfsense_rule_separator.py", line 106, in _ansiballz_main
>         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
>       File "/root/.ansible/tmp/ansible-tmp-1567431318.58-16278943694065/AnsiballZ_pfsense_rule_separator.py", line 49, in invoke_module
>         imp.load_module('__main__', mod, module, MOD_DESC)
>       File "/tmp/ansible_pfsense_rule_separator_payload_N1xzOS/__main__.py", line 90, in <module>
>       File "/tmp/ansible_pfsense_rule_separator_payload_N1xzOS/__main__.py", line 85, in main
>       File "/tmp/ansible_pfsense_rule_separator_payload_N1xzOS/ansible_pfsense_rule_separator_payload.zip/ansible/module_utils/network/pfsense/pfsense_rule_separator.py", line 213, in run
>       File "/tmp/ansible_pfsense_rule_separator_payload_N1xzOS/ansible_pfsense_rule_separator_payload.zip/ansible/module_utils/network/pfsense/pfsense_rule_separator.py", line 145, in _add
>       File "/tmp/ansible_pfsense_rule_separator_payload_N1xzOS/ansible_pfsense_rule_separator_payload.zip/ansible/module_utils/network/pfsense/pfsense_rule_separator.py", line 122, in _get_expected_separator_position
>       File "/tmp/ansible_pfsense_rule_separator_payload_N1xzOS/ansible_pfsense_rule_separator_payload.zip/ansible/module_utils/network/pfsense/pfsense_rule_separator.py", line 106, in _get_separator_position
>       File "/tmp/ansible_pfsense_rule_separator_payload_N1xzOS/ansible_pfsense_rule_separator_payload.zip/ansible/module_utils/network/pfsense/pfsense_rule_separator.py", line 79, in _find_separator
>     AttributeError: 'NoneType' object has no attribute 'find'
>   msg: |-
>     MODULE FAILURE
>     See stdout/stderr for the exact error
>   rc: 1

**Comment by f-bor** [comment]
Hi,

Thanks for reporting.

This should be fixed with the last commit.

Could you please confirm ?

**Comment by WintyBe** [comment]
Hello,

Yes, I can confirm this works now. Thanks!

**Comment by f-bor** [comment]
Thanks again.
