### ISSUE TITLE
Separators not creating on LAN interface

### ISSUE THREAD

**Issue by WintyBe** [opoplawski/ansible-pfsense#28]
Hi,

We use some of these modules to deploy firewalls with a default rulebase and use the  'pfsense_rule_separator' to add some separators. This works perfectly fine on the WAN interface, but once we try to add the separators on the LAN interface, they don't show up. Diving into the config.xml, it seems they are added, but the 'row' is incorrect. 
```
                                <sep0>    
                                        <color>bg-info</color>
                                        <text><![CDATA[Management and Monitoring]]></text>
                                        <row>fr6</row>
                                        <if>lan</if>
                                </sep0>
```
It adds it on fr6, but if I add the same separator correctly, it should be fr0.
```
               <separator>
                        <lan>
                                <sep0>
                                        <row>fr0</row>
                                        <text><![CDATA[Management and Monitoring]]></text>
                                        <color>bg-info</color>
                                        <if>lan</if>
                                </sep0>
                        </lan>
                </separator>
```

I can reproduce this if you need more output. I ran it with -vv but it doesn't give much output apart from telling me it added the separators.

**Comment by f-bor** [comment]
Hi,

could you please give me the parameters for the call to pfsense_rule_separator that is failing ?

I also need your rules and separators definition on the lan interface before that call. I mean something like this:
- 1 sep
- 3 rules
- 1 sep
- 2 rules
...

If you use the after or before parameter, I need to know the position of the target.

**Comment by f-bor** [comment]
Thank you. Unfortunatly, I haven't been able to reproduce.

The fr8 and fr11 values shows that the module thinks there is 8 other rules before.

Would it be possible to see the entire filter section of your config.xml ? (I dont care about the sources and destinations if you mind and want to remove them)

**Comment by WintyBe** [comment]
I think I start to understand. I do have a couple of floating rules, but those had only the LAN interface selected; that is an issue on my end (none should be selected or multiple, but not just LAN) but I believe that is causing the separators to be offset. This is one of them:
```
<filter>
	<rule>
		<type>block</type>
		<tracker>1567429830</tracker>
		<ipprotocol>inet46</ipprotocol>
		**<interface>lan</interface>**
		<direction>any</direction>
		<statetype><![CDATA[keep state]]></statetype>
		<descr><![CDATA[No log HSRP]]></descr>
		<quick>yes</quick>
		<protocol>udp</protocol>
		<floating></floating>
		<source>
			<any></any>
		</source>
		<destination>
			<any></any>
			<port>SVC_HSRP</port>
		</destination>
	</rule>
```
Once I deselected the LAN interface (removing the 'interface' section completely in the above output) or selected an extra interface (like OPT1, resulting in <interface>lan,opt1</interface>) the issue disappears and the separators show up correctly.

**Comment by f-bor** [comment]
Ok. I thought it may be this situation and I did the same configuration in my tests. It worked on my side because the GUI generated the following XML for floating rules:
`<floating>yes</floating>`

But in your case, it's just:
`<floating></floating>`

I will push a fix to handle that but how did you create those rules ? And if it's with GUI with which version of pfSense ?

**Comment by WintyBe** [comment]
Thanks.

I used another module from a different [repository](https://github.com/bevhost/ansible-module-pfsense), I'll log an issue there as well about the '<floating>yes</floating>' thing.

**Comment by f-bor** [comment]
it should be ok now. Can you please confirm ?

**Comment by WintyBe** [comment]
It is indeed solved, thanks a lot.
