### ISSUE TITLE
Pfsense Rule WAN IP and Port

### ISSUE THREAD

**Issue by tysoe27** [opoplawski/ansible-pfsense#29]
For "Destination" (and source I guess) in pfsense_rule, the format seems to be WAN(network):Port or WAN(IP) (without a port). I want to add a rule which has a destination of "WAN Address" and port 443. I tried destination=WANIP:443 but it returns error:

"Cannot parse address WANIP, not IP or alias"

'wanip' is one of the dropdown (select) options on the Pfsense GUI so should work, right?

**Comment by f-bor** [comment]
Hi,

The right syntax is IP:interface:port or NET:interface:port but it was buggy and confused. I fixed that so if you use IP:WAN:443, it should now work correctly.
