### ISSUE TITLE
[Question] How to set NAT firewall rules?

### ISSUE THREAD

**Issue by tvories** [opoplawski/ansible-pfsense#32]
I haven't been able to figure out how to set NAT firewall rules.  Is this possible with the plugin?

**Comment by opoplawski** [comment]
No, we don't yet support NAT rules.

**Comment by f-bor** [comment]
I wrote two modules to manage NAT rules. They do not covert one to one and prefix translation (let me know if you need those).

The documentation is in the wiki: [pfsense_nat_port_forward](https://github.com/opoplawski/ansible-pfsense/wiki/pfsense_nat_port_forward) and [pfsense_nat_outbound](https://github.com/opoplawski/ansible-pfsense/wiki/pfsense_nat_outbound)
