### ISSUE TITLE
pfsense_user won't add user to /etc/group

### ISSUE THREAD

**Issue by majales** [opoplawski/ansible-pfsense#34]
Hi,
First of all I have  to thank you for great tool to manage pfsense. I'm testing it now with adding users to my home pfsense. I have noticed that in web interface user is added right with password, sshkey and group, but it does not change /etc/group file. It affect for example users that have been added to admin group but they cannot run sudo. They finally appear in /etc/group  if you edit any user with removing or adding him to the particular group.

**Comment by f-bor** [comment]
Hi,

I see. It needs some work to be properly fixed (in the way the web interface does). I will try do that soon.

**Comment by opoplawski** [comment]
I believe I've checked in a fix for this.  Unfortunately I had made some mistakes about how group information was stored in the config file so this required changing from using "groupname" (which appears to only be used for the "admin" user) to using "groups" - which is list of all groups the user belongs to.  Please test and let me know, but it appears to be working okay here.

**Comment by opoplawski** [comment]
Note also that it will only sync group information for groups that it believes have changed - so you'll need to make sure that your ansible tasks actually change the group membership from the existing config.  Glad you like the tool so far, hope it continues to work well for you.
