### ISSUE TITLE
openvpn

### ISSUE THREAD

**Issue by matth94** [opoplawski/ansible-pfsense#48]
Hello,
Do you think it would be possible to add modules pfsense-openvpn server and client?

**Comment by f-bor** [comment]
Hello,
It would be nice but for now I don't even have time to implement the modules I need.

**Comment by opoplawski** [comment]
I would like it as well (we use openvpn here), but like f-bor I have limited time as well.  It's really not terribly hard to develop a module if you'd like to try your hand at it.  Some notes are here: https://github.com/opoplawski/ansible-pfsense/wiki/PFSenseModuleBase-Template

**Comment by matth94** [comment]
Bonsoir,

Comme je suis vraiment intéressé, je commence a essayer un peu de mettre en forme ces 2 modules.
Je reviendrai vers vous quand j'aurais besoin de correction de code.

A bientôt



Good evening,

As I am really interested, I am starting to try to shape these 2 modules.
I’ll get back to you when I need a code fix.

See you soon

**Comment by opoplawski** [comment]
Excellent!  Happy hacking..

**Comment by rlenferink** [comment]
Just to chime in: I’d really like this module as well ;) so whenever a review is needed @matth94 let me know

**Comment by matth94** [comment]
Bonjour,

J'ai malheureusement du reprendre tout depuis le début car j'ai mon disque dur qui a crashé. Si cela est trop long pour vous dites le moi mais de mon coté je continue a travailler dessus.

A bientôt.

Hello,

Unfortunately I had to resume everything from the beginning because I have my hard drive which has crashed. If it is too long for you tell me but on my side I continue to work on it.

See you soon.

**Comment by rlenferink** [comment]
Perfect! There's no rush from my side so feel free to continue your work ;) I'll keep myself subscribed to this ticket.

**Comment by devopstales** [comment]
@matth94 any update on this?

**Comment by opoplawski** [comment]
pfsensible/core 0.5.0 will have some initial implementations.  Hopefully I can get that out soon.
