### ISSUE TITLE
Feature Request: System / Advanced - Provisioning

### ISSUE THREAD

**Issue by sf32738** [opoplawski/ansible-pfsense#49]
- Admin Access / webConfigurator / SSL Certificate Assignment
- Admin Access / webConfigurator / Anti-Lockout
- Admin Access / webConfigurator / DNS Rebind Check
- Admin Access / webConfigurator / Disable HTTP_REFERER
- Admin Access / Secure Shell / SSHd Key Only
- Admin Access / Secure Shell / SSH Port
- Admin Access / Login Protection / Whitelist

- Networking / IPv6 Options / Allow IPv6
- Networking / IPv6 Options / Prefer IPv4 over IPv6

- Networking / Network Interfaces / Hardware Checksum Offloading
_We deploy on physical and virtual machines, VMs require this to be checked (true)_ 

- Miscellaneous / Cryptographic & Thermal Hardware / Cryptographic Hardware

- Notifications / E-Mail / * All Fields *

**Comment by opoplawski** [comment]
Pull requests welcome!  :)  Seriously, the main developers are both pretty strapped for time and we work on our own itches.  Creating and tweaking modules is really not that hard to do.  See the wiki for more information.  Thanks.
