### ISSUE TITLE
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

### ISSUE THREAD

**Issue by GrandGarcon** [opoplawski/ansible-pfsense#55]
currently installing the scripts in following GCP instance : Linux ,  4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux . when i run the command there is error as follows : 
 ansible-galaxy collection install pfsensible.core
```
- downloading role 'collection', owned by 
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

```

**Comment by opoplawski** [comment]
What version of ansible-galaxy are you using?  It appears to be too old (I'm guessing 2.8.X instead of 2.9.X which is needed for using collections).
