### ISSUE TITLE
Unbound DNS Resolver

### ISSUE THREAD

**Issue by rlenferink** [opoplawski/ansible-pfsense#56]
I'd like to see a new feature/(module?) for configuring the Host Overrides for Unbound DNS resolver.

**Comment by opoplawski** [comment]
Pull requests welcome! :) Seriously, the main developers are both pretty strapped for time and we work on our own itches. Creating and tweaking modules is really not that hard to do. See the wiki for more information. Thanks.

**Comment by coffeelover** [comment]
I've implemented a working module in my fork, has no tests or validation - so i haven't created a pull request yet. But we use this already in our customer project.

**Comment by devopstales** [comment]
@coffeelover any update on this

**Comment by opoplawski** [comment]
Close down this repository.  @coffeelover if you are still around I would love your contribution to pfsensible/core.
