### ISSUE TITLE
ESP not a valid protocol for firewall rules

### ISSUE THREAD

**Issue by scrubby** [opoplawski/ansible-pfsense#60]
Hi,

I noticed that esp is not accepted as a protocol when creating a rule. When checking the code I saw that more existing protocols are also not accepted. Why aren't al available protocols accepted by the rule module?

**Comment by opoplawski** [comment]
Each protocol requires different input validation.  The developers are focused just on the features they need.  PRs are welcome.

**Comment by opoplawski** [comment]
Actually, as of commit 439a6c3cd21c5f2a5dade99aed0c15f3475e5051 (Jan 18, 2020) esp and many other protocols are accepted.  Reopen if you still have some issue with the esp protocol.
