### ISSUE TITLE
Managing DHCP and unbound - any plans?

### ISSUE THREAD

**Issue by Hr46ph** [opoplawski/ansible-pfsense#62]
It would be grand if dhcp could be managed for example for setting fixed dhcp addresses with hostnames.

Unbound would be cool too, if I deploy guest vm's with fixed ip's (on guest OS level) it would be grand if I can push a hostname to unbound to have it resolved.

Are there any plans to make this work too?

Thanks!

**Comment by opoplawski** [comment]
Pull requests welcome! :) Seriously, the main developers are both pretty strapped for time and we work on our own itches. Creating and tweaking modules is really not that hard to do. See the wiki for more information. Thanks.

**Comment by coffeelover** [comment]
I'm working on unbound.

**Comment by coffeelover** [comment]
My unbound module is somewhat ready (no tests at all, no input validation beside type), i'm building modules for a customer installation. I built so far:
- dns_resolver (unbound)
- dhcp_relay
- squid
- virtual_ip
- hasync
I'm currently working on widgets and will add input validation and tests for all modules to include it here, but you can manually install these modules in addition.

**Comment by ad8lmondy** [comment]
I have put a draft PR here: https://github.com/pfsensible/core/pull/26 for doing DHCP (no unbound though, sorry).

It's a bit rough, so any feedback / help would be very welcome. It does work though!
