### ISSUE TITLE
Feature Request: Provide interface update

### ISSUE THREAD

**Issue by HEG-IT** [opoplawski/ansible-pfsense#64]
Not much of a python guys so not sure if I'm just not using it correctly, but it appears that the pfsense.core.interface only allows creating and removing an interface. Update attempts fail on a "KeyError: 'descr'" message.

**Comment by opoplawski** [comment]
This is supposed to be tested by our test suite, so I'm surprised it's not working.  I've recently updated the pfsensible.core release - can you test with that and see if you are still having problems?  If so, please post your playbook section and relevant section of the initial config.xml.  Thanks.
