### ISSUE TITLE
Ansible - Error using privilege escalation

### ISSUE THREAD

**Issue by Ron-1984** [opoplawski/ansible-pfsense#68]
Hi All
I am new to Ansible, I'm trying to copy a repo file from control node to manage node and got the below error when executing my playbook using privilege escalation

**Error:**
[usser1@server1ansible]$ ansible new -m ping -b
SSH password:
BECOME password[defaults to SSH password]:
10.192.128.201 | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Shared connection to 10.192.128.201 closed.\r\n",
    "module_stdout": "\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

My Ansible configuration file(**Ansible.cfg**) has the below
[defaults]
inventory = ./inventory
ask_pass = true
host_key_checking = false

[privilege_escalation]
become = true
become_method = sudo
become_user = root
become_ask_pass = true

My user has the privilege to execute sudo commands on both the nodes. Please help to fix the error.

Thank you

**Comment by opoplawski** [comment]
You appear to have a general ansible issue, not anything to do with ansible-pfsense.   Please use the ansible support methods, I would suggest https://groups.google.com/g/ansible-project
