### ISSUE TITLE
pfsense 2.5 Support?

### ISSUE THREAD

**Issue by sudheeshb** [opoplawski/ansible-pfsense#69]
I have been using this for a while and it works well with pfsense v2.4.5p1.   I am planning to upgrade to pfsense 2.5.0 CE.  Will it work for pfsense 2.5.0?.  Thanks!

**Comment by opoplawski** [comment]
It's hard to say for sure.  Going through the config.xml migrations  the possible impacts I see are:

* (19.9) ipsec phase1 authentication_method rsasig -> cert
* (20.1) authserver ldap_urltype names change
* (20.2) language name changes zh_HK -> zh_Hans_HK, zh_TW -> zh_Hant_TW
* (20.9) ipsec VTI -> VTIMAP changes
* (21.3) ipsec
  * if reauth_enable then must set reauth_time=0
  * else set reauth_time=lifetime-margintime
```
               /* Auto or IKEv2, rekey items */
                if (($ph1ent['iketype'] == 'ikev2') || ($ph1ent['iketype'] == 'auto')) {
                        if (isset($ph1ent['rekey_enable'])) {
                                /* Disable rekey */
                                $ph1ent['rekey_time'] = "0";
                                $ph1ent['reauth_time'] = "0";
                        } elseif (!empty($ph1ent['margintime'])) {
                                /* If margintime is set, use that to calculate rekey_time */
                                $ph1ent['rekey_time'] = ($ph1ent['lifetime'] - $ph1ent['margintime']);
                        }
                }

                if (!empty($ph1ent['margintime'])) {
                        $ph1ent['rand_time'] = $ph1ent['margintime'];
                }

                /* Older snaps had over_time, now need lifetime back. */
                if (!empty($ph1ent['over_time']) && empty($ph1ent['lifetime'])) {
                        $ph1ent['lifetime'] = $ph1ent['over_time'] + max($ph1ent['rekey_time'], $ph1ent['reauth_time']);
                }

                unset($ph1ent['reauth_enable'], $ph1ent['rekey_enable'], $ph1ent['margintime'], $ph1ent['over_time']);
```

So, some significant changes for ipsec and some minor changes for authserver_ldap and setup language.  We'll have think about how we want to handle this.  We have generally said that we will only support the latest version - and that may remain the case.  Or we could possibly multiple versions if it's seen as needed and not too hard.  It will be interesting to see how quickly 2.5.0 is adopted.

**Comment by sudheeshb** [comment]
Thanks!. 

-> We have generally said that we will only support the latest version.

This means you have plans to add support for 2.5.0 as that is the latest version now?.  Any time frame in mind?

**Comment by opoplawski** [comment]
We will certainly work on supporting 2.5.0.  I've put in a fix for pfsense_authserver_ldap already.  @f-bor is the author of the ipsec modules though and I don't make use of them so I'll let him speak to that.

**Comment by f-bor** [comment]
For now, I need to support 2.4.x for my own use.

I have added a quick is_version function in my last commit to check pfSense version and to behave accordingly.

I will work on 2.5.0 support this weekend and on pfSense+ next week.

**Comment by sudheeshb** [comment]
Thanks!. I also plan to delay  pfSense 2.5.0 upgrade process because of  the reported issues.   Will wait for another one or two week before the upgrade. Hopefully ansible support will ready by that time,

**Comment by f-bor** [comment]
It should be ok for ipsec. I have added the new timing parameters and two others I need (NAT-T port and duplicate endpoints).

Which modules are you using besides pfsense_rule and pfsense_alias ?

**Comment by sudheeshb** [comment]
As of now I am using only  interface, alias and rules.

**Comment by f-bor** [comment]
ok. Interface is probably broken. I'll try to look into it soon.

**Comment by WintyBe** [comment]
I can also add _vlan_ is also not working anymore on 2.5.0, this is a traceback:

```
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1614158049.2535503-16828-128613194911594/AnsiballZ_pfsense_vlan.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1614158049.2535503-16828-128613194911594/AnsiballZ_pfsense_vlan.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1614158049.2535503-16828-128613194911594/AnsiballZ_pfsense_vlan.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.pfsense_vlan', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_pfsense_vlan_payload_io8q3ga8/ansible_pfsense_vlan_payload.zip/ansible/modules/pfsense_vlan.py", line 87, in <module>
  File "/tmp/ansible_pfsense_vlan_payload_io8q3ga8/ansible_pfsense_vlan_payload.zip/ansible/modules/pfsense_vlan.py", line 81, in main
  File "/tmp/ansible_pfsense_vlan_payload_io8q3ga8/ansible_pfsense_vlan_payload.zip/ansible/module_utils/network/pfsense/vlan.py", line 44, in __init__
  File "/tmp/ansible_pfsense_vlan_payload_io8q3ga8/ansible_pfsense_vlan_payload.zip/ansible/module_utils/network/pfsense/pfsense.py", line 648, in php
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
failed: [localhost -> 192.0.2.65] (item=1502) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "1502",
    "module_stderr": "Shared connection to 192.0.2.65 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1614158049.2535503-16828-128613194911594/AnsiballZ_pfsense_vlan.py\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1614158049.2535503-16828-128613194911594/AnsiballZ_pfsense_vlan.py\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1614158049.2535503-16828-128613194911594/AnsiballZ_pfsense_vlan.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.pfsense_vlan', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/local/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_pfsense_vlan_payload_io8q3ga8/ansible_pfsense_vlan_payload.zip/ansible/modules/pfsense_vlan.py\", line 87, in <module>\r\n  File \"/tmp/ansible_pfsense_vlan_payload_io8q3ga8/ansible_pfsense_vlan_payload.zip/ansible/modules/pfsense_vlan.py\", line 81, in main\r\n  File \"/tmp/ansible_pfsense_vlan_payload_io8q3ga8/ansible_pfsense_vlan_payload.zip/ansible/module_utils/network/pfsense/vlan.py\", line 44, in __init__\r\n  File \"/tmp/ansible_pfsense_vlan_payload_io8q3ga8/ansible_pfsense_vlan_payload.zip/ansible/module_utils/network/pfsense/pfsense.py\", line 648, in php\r\n  File \"/usr/local/lib/python3.7/json/__init__.py\", line 348, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"/usr/local/lib/python3.7/json/decoder.py\", line 337, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"/usr/local/lib/python3.7/json/decoder.py\", line 355, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)\r\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by f-bor** [comment]
it seems you are not running the last version of our modules. Can you update them and try again ?

**Comment by WintyBe** [comment]
> 
> 
> it seems you are not running the last version of our modules. Can you update them and try again ?

I indeed wasn't, I noticed it right after commenting, so I deleted my comment in the meantime. It works fine now :)

**Comment by opoplawski** [comment]
@f-bor ipsec tests are failing with missing fixtures.  Could you fix that please?  Thanks.

**Comment by f-bor** [comment]
Sorry about that. It's fixed.

**Comment by opoplawski** [comment]
Are there any remaining 2.5 support issues to be addressed?

**Comment by opoplawski** [comment]
Just as a heads up - I will be on vacation Mar 20-26 and offline.

**Comment by coffeelover** [comment]
Also for authserver_ldap: There is a new setting "Shell Authentication" (https://github.com/pfsense/pfsense/blob/master/src/etc/inc/auth.inc#L2306) that allows with `pam_ldap_groupdn` to limit the login to group members also on shell.

**Comment by hambuergaer** [comment]
The aggregate module is currently not working properly on 2.5.0 is_jumbo_capable is now implemented differently on pfSesne side. Due to this reason the vlan plugin which is called by the aggregate module fails.

**Comment by f-bor** [comment]
@hambuergaer this was fixed just after the release of 2.5.0. Are you working with a recent version of our modules ?

**Comment by hambuergaer** [comment]
@f-bor : I am using https://galaxy.ansible.com/pfsensible/core version 0.4.1 and it`s not working for me.

**Comment by hambuergaer** [comment]
@f-bor : the fix seems not to be included in the current version available on Ansible Galaxy. But I see the fix already in the Git repo. When do you expect to release a new version in Ansible Galaxy?

**Comment by f-bor** [comment]
@hambuergaer I don't know. opoplawski manages that part.

In the meantime, you can build & install the collection from pfsensible repository with the following:
```
git clone https://github.com/pfsensible/core.git
cd core
ansible-galaxy collection build
ansible-galaxy collection install pfsensible-core-0.4.1.tar.gz --force

```

**Comment by opoplawski** [comment]
@hambuergaer 0.4.2 has been pushed to galaxy.  Should have all the latest code.

**Comment by coffeelover** [comment]
@opoplawski @f-bor I have added the settings for pfsense_setup and pfsense_auth_server_ldap (shell auth) for systems >=2.5.0.
I'm using the is_at_least_2_5_0 function for the new settings.

**Comment by locose-dev** [comment]
@f-bor seems there is an issue when creating multiple VTI interfaces because of the change in ipsec numbering in 2.5 

First interface works fine then afterward the interfaces just get over written. as they are both just ipsec
not sure if this has already been addressed and i'm missing something. 
thanks

**Comment by therevoman** [comment]
Ran into an issue with the play `pfsense_setup.yaml` with 2.5.2.   
python is 3.8
`ansible_python_interpreter=/usr/local/bin/python3.8`

the `nss_pam_ldap` stuff is no longer valid, also adding the package `py27-ipaddress`
`nslcd` is no longer installed or available.

Also `pkg add` has changed to `pkg install`

**Comment by opoplawski** [comment]
I'm going to close this issue because there is just too much in it at this point.  Please file individual issues for other problems.

I've updated the README to indicate issues with python 3.8 discovery.
