### ISSUE TITLE
using ca module in pfsense 2.5

### ISSUE THREAD

**Issue by mnestor** [opoplawski/ansible-pfsense#71]
We now get warnings of usage of write_config() without a description. Should probably add what cert is added/updated/removed in the call.

https://github.com/opoplawski/ansible-pfsense/blob/7a2aa38dba44d1ff0561aba47ee4b8ae08bf627f/library/pfsense_ca.py#L248

**Comment by opoplawski** [comment]
Hopefully resolved.  Not really sure how useful the description messages are so I didn't go out of the way to make it too meaningful.  Thanks for the report.
