### ISSUE TITLE
pfsensible.core not compatible with ansible.netcommon 2.0.0

### ISSUE THREAD

**Issue by vash666** [opoplawski/ansible-pfsense#72]
Hello,

Ansible Netcommon 2.0.0 has been released 2 days ago but it seems that the module module_utils.compat.ipaddress has been removed from this version of netcommon.

I'm getting this error while launching the playbook with the pfsensible.core collection:

`fatal: [pfsense-lab]: FAILED! => {"msg": "Could not find imported module support code for ansible_collections.pfsensible.core.plugins.modules.pfsense_alias.  Looked for (['ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress.IPv4Address', 'ansible_collections.ansible.netcommon.plugins.module_utils.compat.ipaddress'])"}`

I have downgraded the netcommon to 1.5.0 and it's working fine.

**Comment by opoplawski** [comment]
This should be fixed now.  Just depending on system ipaddress now.
