### ISSUE TITLE
Problem with pfsense_authserver_ldap module - automatically change LDAP config ?

### ISSUE THREAD

**Issue by LaMagouille98** [opoplawski/ansible-pfsense#76]
Hello, 

I have problem with pfsense_authserver_ldap module. When I run the script I made from this module for automatic LDAP configuration, everything is fine without any errors. 
But the problem is that the configuration does not apply and is still set to Local Database. 

Is there a way to change this setting without going through the web GUI manually? 

I have tried making changes directly to the /cf/conf/config.xml file but the configuration still does not apply. 

Thank you in advance for your feedback

**Comment by coffeelover** [comment]
This is done via GUI on System->User Manager->Settings by the Dropdown Authentication Server.

This can be done via Ansible (**after my pull request has been merged**) with pfsense_setup:
```
pfsensible.core.pfsense_setup:
  authmode: "my ldap server"
```

**Comment by opoplawski** [comment]
This should be fixed now with https://github.com/pfsensible/core/commit/e8cda05664306b3b926d373b8c16c7bf9aca311f
