### ISSUE TITLE
[Feature reqest] Adding an User

### ISSUE THREAD

**Issue by tyl0re** [opoplawski/ansible-pfsense#8]
It would be great if it would be possible to add User. 
So VPN access can be Created Automatically (When no LDAP is aviable)

**Comment by opoplawski** [comment]
FWIW - I have an extremely limited amount of time to work on this project, so I'm only going to be working on features that I need.  PRs are welcome.

**Comment by f-bor** [comment]
@tyl0re in addition to creating new users, which settings would you need to set on those users to achieve what you need ?

**Comment by Blaiserman** [comment]
I Created new users on the BSD side but this users can't login on the webUI. Pfsense store the webUI user setting (and other setting) in the /conf/config.xml

**Comment by opoplawski** [comment]
There is some initial pfsense_user support, though I don't think it is nearly complete.

**Comment by opoplawski** [comment]
FYI - checked in some changes to the pfsense_user task so hopefully it properly handles setting group membership now.  I'm going to close this now.  If there are particular things you need the pfsense_user task module to be able to do, please file a separate request for them.  Thanks!
