### ISSUE TITLE
pfsense_ipsec_p2 module overwriting other p2 interfaces in 2.5.2

### ISSUE THREAD

**Issue by devcose** [opoplawski/ansible-pfsense#80]
Hi i mentioned this in #69 but seems an old post so will open a new issue. 

When creating multiple ipsec phase2 interfaces there is a problem when creating the interface meaning they are not id'd correctly so the interfaces are overwritten. so can not be assigned 

I tested this in 2.4.5 and works as intended as the ipsec interfaces are labled ipsec1000, ipsec2000 
however in 2.5.2 each interface is labled ipsec, ipsec and so on. 

it's possible i'm missing something obvious but the same yml yielded the above results on the different versions. 

If you need more details let me know and will be happy to provide. 
thanks

**Comment by opoplawski** [comment]
Closed in favor of pfsensible/core#29
