### ISSUE TITLE
ERROR! 'pfsense_rule' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by slybreiz** [opoplawski/ansible-pfsense#91]
Hello
I have a problem with pfensible:

root@ansible-reseaux:~/ansible/193-ansible-pcaptif# ansible-playbook port-49400.yml -l 10.144.250.233 -vvv
ansible-playbook [core 2.12.6]
  config file = /home/ansible/193-ansible-pcaptif/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/ansible/193-ansible-pcaptif/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
Using /home/ansible/193-ansible-pcaptif/ansible.cfg as config file
host_list declined parsing /home/ansible/193-ansible-pcaptif/inventories/hosts as it did not pass its verify_file() method
script declined parsing /home/ansible/193-ansible-pcaptif/inventories/hosts as it did not pass its verify_file() method
auto declined parsing /home/ansible/193-ansible-pcaptif/inventories/hosts as it did not pass its verify_file() method
Parsed /home/ansible/193-ansible-pcaptif/inventories/hosts inventory source with ini plugin
ERROR! 'pfsense_rule' is not a valid attribute for a Play

The error appears to be in '/home/ansible/193-ansible-pcaptif/port-49400.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: "rajout du port 49400 pour client pronote"
  ^ here
root@ansible-reseaux:~/ansible/193-ansible-pcaptif#

**Comment by opoplawski** [comment]
Looks like either you haven't installed pfsensible properly or your play is incorrect.  You may need to specify the full name for the module: `pfsensible.core.pfsense_rule`.  If you are sure you have installed it properly, please file an issue here: https://github.com/pfsensible/core/issues
